
version: 2

models:
  - name: t_schedule
    description: "Parsed/normalized json matchup info from schedule_raw"
    columns:
      - name: game_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: venue_id
        description: "Foreign key referencing t_venue_d venue_id"
        data_tests:
          - relationships:
              to: ref('t_venue_d')
              field: venue_id

  - name: t_venue_d
    description: "Cleaned game venue info from schedule_raw"
    columns:
      - name: venue_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: t_broadcast_d
    description: "Cleaned game broadcast info from schedule_raw"
    columns:
      - name: game_id
        description: "The primary key for this table"
        data_tests:
          - not_null

  - name: t_playtype_d
    description: "Cleaned game broadcast info from plays_raw"
    columns:
      - name: playtype_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: t_plays
    description: "Cleaned gameplay info from plays_raw"
    columns:
      - name: play_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: t_team_d
    description: "Cleaned team details from teams_raw"
    columns:
      - name: team_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
